site_name: RenderPi - GameCreator2 Tools
theme:
  name: material
  features:
#    - navigation.tabs
    - navigation.sections
    - toc.integrate
#    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

  plugins:
    - social
    - search

  extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/james-willett      
nav:
  - Home: 'index.md'
  - 'GC2 Sub Systems':
    - 'Flag List': 'flag-list-system.md'
  #   - 'First Person Interaction': 'first-person-interaction.md'
  # - About:
  #   - 'License': 'license.md'
  #   - 'Release Notes': 'release-notes.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  generator: false
copyright: Copyright &copy; 2020 - RENDERPI LTD